### ISSUE TITLE
"Unpublished" or "hidden" pages still can be access through the URL

### ISSUE THREAD

**Issue by think-tanker-alex** [wanze/TemplateEngineFactory#8] opened 2017-09-29 09:39 UTC
When using the TemplateEngineFactory, I noted that unpublishing or hiding pages does not work as intended: These pages still can be accessed directly through their URL.

I do not know the root-cause for this, but I think it is related to the TemplateEngineFactory module.

I use ProcessWire 3, and the Template Engine Twig module.

**Comment by MicahStevens** [comment] 2017-10-05 00:20
I just checked in my installation, PW3 w/Twig and it's working for me, unpublished pages give a 404 error. Hidden pages still display, but I believe that's intended, they just won't be returned in searches.

**Comment by wanze** [comment] 2018-03-18 19:19
@think-tanker-alex 

I also ran a few tests and cannot reproduce your problems, so i guess the issue on your end is not caused by this module. Like @MicahStevens pointed out, hidden pages are still accessible, they are just hidden from `$pages->find()` API calls. Also note that unpublished pages do NOT result in a 404 if you are logged in - always test with the anonymous user, e.g. inkognito or second browser.

**Closed as completed by wanze** 2018-03-18 19:19 UTC
